version: 2.1

commands:
  deploy-app:
    parameters:
      envname:
        default: "tools"
        type: string
    steps:
      - checkout
      - install-cloud-foundry
      - run:
         name: CloudGov Deploy
         command: |
           cf login -a https://api.fr.cloud.gov -u $CF_SERVICE_USER -p $CF_SERVICE_PASS -s << parameters.envname >>
           ./bin/deploy-logshipper.sh

  setup-services:
    steps:
      - run:
          name: Set up services
          command: |
            ./bin/setup-services.sh

  create-route:
    steps:
      - run:
          name: Create and bind route
          command: |
            cf create-route app.cloud.gov --hostname usagov-tools-logshipper
            cf map-route log-shipper usagov-tools-logshipper.app.cloud.gov

  bind-services:
    steps:
      - run:
          name: Bind services to app
          command: |
            cf bind-service log-shipper newrelic-creds
            cf bind-service log-shipper cg-logshipper-creds
            cf bind-service log-shipper log-storage

  set-proxyroute:
    steps:
      - run:
          name: Set PROXYROUTE and restart
          command: |
            cf target -s shared-egress 2>&1 > /dev/null
            proxyroute=$(cf env tools-proxy | grep proxy_route | awk '{print $2}')
            if [ -z "$proxyroute" ]; then
                 echo "Unable to find route to proxy app for this space"
                 exit 1
            fi
            cf target -s tools
            cf set-env log-shipper PROXYROUTE $proxyroute
            cf restart log-shipper --strategy rolling

  install-cloud-foundry:
    steps:
      - run:
          name: Install Cloud Foundry
          command: |
            if command cf > /dev/null; then echo "CF client already installed"; exit 0; fi
            wget --user-agent="Mozilla" -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
            echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
            sudo apt-get update
            sudo apt-get install cf8-cli
            cf -v

workflows:
  version: 2

  deploy-logshipper:
    jobs:
      - approve-deploy:
          type: approval
      - deploy-app-to-cloudgov-tools:
          requires:
            - approve-deploy

  setup-services-and-deploy:
    when:
      equal: [ launch, << pipeline.parameters.action >> ]
    jobs:
      - approve-launch:
          type: approval
      - setup-services-and-deploy-app:
          requires:
            - approve-launch

jobs:
  deploy-app-to-cloudgov-tools:
    machine:
      image: ubuntu-2004:2023.10.1
      resource_class: medium
    steps:
      - checkout
      - install-cloud-foundry
      - deploy-app:
          envname: "tools"

  setup-services-and-deploy-app:
    machine:
      image: ubuntu-2004:2023.10.1
      resource_class: medium
    steps:
      - checkout
      - install-cloud-foundry
      - setup-services
      - deploy-app:
          envname: "tools"
      - create-route
      - bind-services
      - set-proxyroute
